# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{
  config,
  lib,
  modulesPath,
  pkgs,
  ...
}:

{
  imports = [
    (modulesPath + "/installer/scan/not-detected.nix")
  ];

  boot.initrd.availableKernelModules = [
    "nvme"
    "xhci_pci"
    "thunderbolt"
    "usb_storage"
    "sd_mod"
    "sdhci_pci"
  ];

  boot.kernelModules = [ "kvm-amd" ];
  boot.extraModulePackages = [ ];
  boot.kernelParams = [
    # ─── IOMMU ───────────────────────────────────────────────────────────────────
    # Passthrough mode: required for KVM/QEMU, keeps IOMMU active but non-strict.
    # Note: this keeps IOMMU active during suspend — acceptable tradeoff for virt.
    "amd_iommu=pt"
    "iommu=pt"

    # ─── MEMORY LIMIT ────────────────────────────────────────────────────────────
    # Caps pinned memory to 112 GiB (16GiB left for the OS)
    "ttm.pages_limit=29360128"

    # ─── AMDGPU STABILITY (Strix Halo / Strix Point essential fixes) ──────────────
    # Disables scatter-gather display — REQUIRED on systems with >16GB RAM.
    # Without this you get VPE/Ring crashes and memory corruption.
    "amdgpu.sg_display=0"

    # Disable PSR (Panel Self Refresh, 0x10) and DSC (Display Stream Compression, 0x4).
    # Fixes screen glitches on Strix Halo. Safer than 0x104 which skips PSR.
    # Disabled for laptop battery life because it allows the GPU to sleep when the screen is static
    # "amdgpu.dcdebugmask=0x14"

    # Ensure AMD Display Core is enabled (should be default, but explicit is safer).
    "amdgpu.dc=1"

    # Fixes "mes ring buffer is full" kernel errors on Strix.
    # Tradeoff: disabling CWSR slightly impacts GPU power state transitions.
    "amdgpu.cwsr_enable=0"

    # ─── GPU POWER MANAGEMENT ────────────────────────────────────────────────────
    # Enable GPU runtime power management — essential for proper suspend/resume.
    "amdgpu.runpm=1"

    # Bootstrap APM: improves APU-level power management on integrated graphics.
    "amdgpu.bapm=1"

    # Active State Power Management for the GPU's PCIe link.
    # Disabled to avoid input lag.
    "amdgpu.aspm=0"

    # Disable autosuspend for Bluetooth USB devices.
    "btusb.enable_autosuspend=0"

    # ─── SUSPEND / S0ix ──────────────────────────────────────────────────────────
    # Use modern standby (S0ix / s2idle) — the only suspend mode Strix Halo supports.
    # S3 (deep) is not available on this platform.
    "mem_sleep_default=s2idle"

    # Prevents NVMe drives from blocking S0ix entry.
    # High latency tolerance on NVMe can stall the PMC from reaching deep sleep.
    # "nvme_core.default_ps_max_latency_us=0"

    # ─── PCIe POWER MANAGEMENT ───────────────────────────────────────────────────
    # Force PCIe ASPM negotiation and use the most aggressive power policy.
    # Helps all PCIe-attached devices (NVMe, WiFi, etc.) reach low-power states
    # before the PMC can gate the SoC — directly addresses the S0ix blocker.
    # "pcie_aspm=force"
    # "pcie_aspm.policy=powersupersave"

    # ─── USB AUTOSUSPEND ─────────────────────────────────────────────────────────
    # Allow USB devices to autosuspend after 1 second of inactivity.
    # XHCI controllers staying active is one of the most common S0ix blockers.
    # "usbcore.autosuspend=1"
  ];
  fileSystems."/" = {
    device = "/dev/disk/by-uuid/610f9caa-d492-41d8-80a5-1ba3bf7b7ba6";
    fsType = "btrfs";
    options = [ "subvol=@" ];
  };

  boot.initrd.luks.devices."luks-6505edc5-61f3-4598-a3ef-2c20f4fcc236".device =
    "/dev/disk/by-uuid/6505edc5-61f3-4598-a3ef-2c20f4fcc236";
  boot.initrd.luks.devices."luks-6606e271-2d02-4664-a7b5-4d0783dc2cc1".device =
    "/dev/disk/by-uuid/6606e271-2d02-4664-a7b5-4d0783dc2cc1";
  fileSystems."/boot" = {
    device = "/dev/disk/by-uuid/973E-E46E";
    fsType = "vfat";
    options = [
      "fmask=0077"
      "dmask=0077"
    ];
  };

  swapDevices = [
    { device = "/dev/disk/by-uuid/c255ed76-3b24-4eb1-9593-44fa81314a63"; }
  ];

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.wlp99s0.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.enableRedistributableFirmware = true;
  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
  hardware.graphics = {
    enable = true;
    enable32Bit = true;
  };
  hardware.amdgpu.opencl.enable = true;
  hardware.amdgpu.initrd.enable = true;
  # AI Environment Variables for Strix Point ROCm compatibility
  environment.variables = {
    HSA_OVERRIDE_GFX_VERSION = "11.5.0"; # Spoofs GPU for ROCm support
  };
  services.lact.enable = true;

}
