user := env('user', 'root')

# Initialize tofu keys and backends
[group('setup')]
init:
    #!/usr/bin/env bash
    set -euxo pipefail
    if [ ! -d .terraform ]; then
        printf "Initializing tofu...\n"
        tofu init \
            -backend-config="access_key=$(yq --input-format toml -o toml '.scw_access_key' terraform.tfvars)" \
            -backend-config="secret_key=$(yq --input-format toml -o toml '.scw_secret_key' terraform.tfvars)"
    else
        printf "tofu already up, maybe try run upgrade\n"
    fi
    if [ ! -f terraform.tfvars ]; then
        printf "Initializing tofu variables...\n"
        terraform-docs tfvars hcl . > terraform.tfvars
        printf "Fill the variables with the correct info\n"
    else
        printf "tofu variables already initialized.\n"
    fi

# Run tofu plan
[group('infra')]
plan:
    tofu plan

# Create or update infrastructure
[group('infra')]
apply:
    tofu apply -auto-approve

# Update drivers (scaleway, porkbun, etc)
[group('infra')]
upgrade:
    tofu init -upgrade

# Destroy all
[group('infra')]
destroy-server:
    tofu destroy -auto-approve
    # tofu destroy -target=scaleway_instance_server.amaru -auto-approve

# Show cloud init logs
[group('ops')]
cloud-logs ip=`just outputs | jq -r '.public_ips.value[0].address'`:
    ssh "root@{{ ip }}" cloud-init status --long
    ssh "root@{{ ip }}" cat /var/log/cloud-init-output.log

# Read and save the cloud-init logs, can run hot
[group('ops')]
save-logs ip=`just outputs | jq -r '.public_ips.value[0].address'`:
    sleep 60
    ssh -o StrictHostKeyChecking=accept-new "root@{{ ip }}" "tail -f -n +1 /var/log/cloud-init-output.log" | tee .logs/cloud-init-output.log

debug-nixos-bite ip=`just outputs | jq -r '.public_ips.value[0].address'`:
    sleep 60
    ssh -o StrictHostKeyChecking=accept-new "root@{{ ip }}" "NIX_INSTALLER=experimental NIX_DNS=2a00:1098:2c::1 bash /root/nixos-bite.sh reboot" 2>&1 | tee .logs/bite-logs

# SSH to host
[group('ops')]
ssh host='amaru' user=user cmd=env('cmd', ''):
    @IP=$(just outputs | jq -r '.{{ host }}_ssh.value'); \
    ssh -o StrictHostKeyChecking=accept-new "{{ user }}@${IP}" {{ cmd }}

# Print tofu outputs
[group('ops')]
outputs:
    @tofu output -json

# UNUSED, I leave it for posterity
[group('setup')]
vm-nixify host='amaru' ip=`just outputs | jq -r '.public_ips.value[0].address'`:
    @mkdir -p .logs
    nix run github:nix-community/nixos-anywhere -- \
      --flake "..#{{ host }}" \
      --generate-hardware-config nixos-generate-config \
      "../hosts/{{ host }}/hardware-vm.nix" \
      "root@{{ ip }}" | tee .logs/vm.logs

# Apply the Nix configuration as root (user will change, do it once)
[group('setup')]
vm-apply-as-root host='amaru' user=user:
    #!/usr/bin/env sh
    IP=$(just outputs | jq -r '.{{ host }}_ssh.value')
    mkdir -p .logs
    nh os switch --show-trace --elevation-strategy passwordless --target-host "{{ user }}@[${IP}]" --hostname "{{ host }}" ../

# Provision the VM
[group('setup')]
provision host='amaru':
    just apply
    sleep 720 # 6 min
    just vm-apply-as-root "{{ host }}"

# Get SSH public key
[group('sec')]
pub-shh host='amaru' user=user:
    #!/usr/bin/env sh
    IP=$(just outputs | jq -r '.{{ host }}_ssh.value')
    ssh "{{ user }}@${IP}" cat /etc/ssh/ssh_host_ed25519_key.pub
